spring:
  application:
    name: user-admin
  # 数据库配置
  # datasource:
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  #  url:
  #  username:
  #  password:
  profiles:
    active: local
  session:
    timeout: 21600 # 15天
  data:
    redis:
      host: your-redis-host
      port: 6379
      database: 0

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.dingzk.useradmin.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
    # SQL 日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1